### ISSUE TITLE
No longer support?

### ISSUE THREAD

**Issue by rafaelbertelli** [react-native-community/react-native-audio-toolkit#124]
Hello friends,

I realize that this lib is no longer being updated by @futurice.
I don't know if it's possible (I am a noob at open source yet), but i'd like to suggest to open this lib to the community keep it, because this is one of the best audio libs that I've found to RN.

Thanks

**Comment by kesha-antonov** [comment]
@FruitieX Hey
What do you think? I can review PRs

**Comment by moonstruck** [comment]
https://github.com/futurice/react-native-audio-toolkit/pull/115#issuecomment-437903266

**Comment by kesha-antonov** [comment]
I emailed to the owner of repo and company. If they'll respond I will write here

**Comment by kesha-antonov** [comment]
I ended up using react-native-video for my audio files

**Comment by moonstruck** [comment]
https://github.com/react-native-kit/react-native-track-player is a great module if you need background support.

**Comment by xstable** [comment]
This Component seems not to be under maintenance anymore.
I've wrote an Mail to @futurice like @kesha-antonov ... no response at all.

Maybe somebody who wan't to take over this Project could write an issue with 
**BIG-LETTERS:** 
_Not maintained anymore... takeover to: https://github.com/xxxx/xxxxx_

@kesha-antonov || @FruitieX do you like to take over this Project?

(Thumbs-Up for all who agree to take over this nice Project and bring it back to live)

**Comment by kesha-antonov** [comment]
I think we should move it under https://github.com/react-native-community
@xstable

**Comment by xstable** [comment]
@kesha-antonov Sounds good.

**Comment by moonstruck** [comment]
moving to react-native-community would be great!

**Comment by xstable** [comment]
@kesha-antonov Can you start the take-over? What steps are needed? (I'm not yet take over any project to react-native-community)

**Comment by kesha-antonov** [comment]
@xstable I'm in the same boat. I don't know what to do.
Let's call here some maintainers from repos of react-native-community

**Comment by kesha-antonov** [comment]
https://github.com/orgs/react-native-community/people

**Comment by kesha-antonov** [comment]
@sibelius
@satya164
@oblador
@Kureev
@ide

Hey guys! Can you help us here?
How to move this repo to RN-community?

**Comment by FruitieX** [comment]
This sounds like a good idea, thumbs up from me :+1:

**Comment by satya164** [comment]
Happy to do that, but to move the repo, we need permission from the maintainers :D

**Comment by xstable** [comment]
@FruitieX Do you have a clue how to contact them? I've send them a mail like @kesha-antonov did, but got no response at all.

**Comment by tino-junge** [comment]
Hi everyone, 

thanks for your interest to continue maintaining this project :) 
I'll have a chat with our Futurice IT team to sort out the ownership.

**Comment by kimmoahokas** [comment]
Hello all,

Thanks for the interest. Let's indeed move the repo to community. Is there something special you would like me to do or shall I just start the ownership transfer to https://github.com/react-native-community ?

**Comment by kesha-antonov** [comment]
@satya164

**Comment by sibelius** [comment]
you can transfer to @satya164 and he can transfer to the community

**Comment by satya164** [comment]
yea, lemme know when you transfer to me and I'll transfer to the community.

**Comment by kimmoahokas** [comment]
@satya164 I requested the trasfer to you. I had to transfer the repository first to myself as our organisation settings did not allow direct transfer to you.

**Comment by satya164** [comment]
It's done.

**Comment by satya164** [comment]
Also if anyone wants push access to the repo for maintaining, let me know.

**Comment by kimmoahokas** [comment]
Awesom, thank you!

**Comment by hisankaran** [comment]
Great to see that this lib is now maintained by react-native-community. Should we roll-out an update to NPM as well? https://www.npmjs.com/package/react-native-audio-toolkit.

**Comment by hisankaran** [comment]
@kesha-antonov @satya164 I can review PRs as well.

**Comment by sibelius** [comment]
@brentvatne can you give me admin permission on this repo, so I can invite more people to contribute?

**Comment by satya164** [comment]
@sibelius done

**Comment by sibelius** [comment]
invited everybody in this thread to contribute to this repo

we can start reviewing issues and pull requests and then move forward on new issues and features

**Comment by brentvatne** [comment]
perhaps this can be made a js-only lib that depends on https://github.com/expo/expo/blob/master/packages/expo-av/README.md in order to consolidate efforts? i think expo-av can do everything this lib can + other stuff - https://docs.expo.io/versions/v32.0.0/sdk/audio/

**Comment by hisankaran** [comment]
@brentvatne If I am not wrong, expo-av does not support audio recording while in background.

**Comment by brentvatne** [comment]
cc @sjchmiela

**Comment by sjchmiela** [comment]
Since SDK33 Expo does support recording audio while in background. Hooray! 🎉

**Comment by sbeca** [comment]
Hi @tino-junge and @kimmoahokas, I have done a bunch of work on improving this library since I was added as a collaborator and I would like to push a version 2.0.0 to npm but I believe that Futurice is still the only ones who can push this package to npm. Would it be possible to add me as a collaborator on npm for this package? My npm user name is scott.beca

**Comment by kimmoahokas** [comment]
@xstable I think the best way forward here is to move the npm package out from Futurice organisation as well. Would there be some react native community org in npm where this should go to? I can help with the transfer from our end.

I'm not going to give anyone outside Futurice access to any package in our organisation.

**Comment by xstable** [comment]
@kimmoahokas @sbeca have no clue about this, and not yet much familiar with npm-ownership. 
I only seen that there are also Packages like: @react-native-community/cli... which could mean, that you can transfer the npm-ownership to @react-native-community on npm too.

Better somebody which have a better clue about npm should research and answer this.

**Comment by sbeca** [comment]
After talking with a number of react-native-community members, we think that this is the best way forward:

1. I will publish v2.0.0 to NPM as a new NPM package: `@react-native-community/audio-toolkit`
2. After step 1 is done, someone from Futurice will publish v1.0.7 to NPM under the current NPM package, which will just be the current version with a deprecation warning pointing to the new version.

We think this is the best solution as we would like react-native-community packages to eventually all move to namespaced package names. But if we just directly transfer an old package name to a new one, then old users of the package may be lost or not notified of the new package, hence step 2 with the deprecation warning.

Would you be happy with this @kimmoahokas and @xstable? If so, then I will move forward with doing step 1 and then let you know when you should do step 2.

**Comment by kimmoahokas** [comment]
Thanks @sbeca. Sounds really good to me.

**Comment by xstable** [comment]
I'm fine with this.

**Comment by kimmoahokas** [comment]
Hi. I noticed that this was left hanging. Sorry about that. I just deprecated https://www.npmjs.com/package/react-native-audio-toolkit in favor of https://www.npmjs.com/package/@react-native-community/audio-toolkit

**Comment by danieloi** [comment]
> Since SDK33 Expo does support recording audio while in background. Hooray! 🎉

You still don't get decibel information in expo-av if you want to make a visualization when you're using the recorder.
