### ISSUE TITLE
The minSdk version should not be declared in the android manifest file

### ISSUE THREAD

**Issue by suther** [react-native-community/react-native-audio-toolkit#130]
While trying to build my app, I got this Error: 

> ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
> Remove minSdkVersion and sync project
> Affected Modules: react-native-audio-toolkit

So please remove it to fix this bug.

**Comment by sibelius** [comment]
fixed
