### ISSUE TITLE
Unexpected recording from device microphone instead of Bluetooth when connected

### ISSUE THREAD

**Issue by pottercomuneo** [react-native-community/react-native-audio-toolkit#133]
Hi community!
As per the title of the issue, when I connect the device to a Bluetooth input/output, my app correctly transmits the audio to the Bluetooth device but when I'm recording it's the device microphone instead of the Bluetooth one.
Does anyone know how to force the Bluetooth microphone to be the source?
Thanks!

**Comment by HyunMook** [comment]
I have the same issue. If I move to another screen while recording is working, I can't listen to every sound using Bluetooth.

**Comment by pottercomuneo** [comment]
Solved on my own! In `AudioRecorder.m`, I've added the Bluetooth in line 80, which now appears like this:
```
[audioSession setCategory:AVAudioSessionCategoryRecord withOptions:AVAudioSessionCategoryOptionAllowBluetooth error:&error];
```

**Comment by defrian** [comment]
I am facing the same issue but only on iPhone device and recording via AirPods.
Running the app in the simulator on my Mac, recoding via AirPods works

I tried to run the app on device and debug it remotely.
No error in the console, but recoding via AirPods is not working

What could I try to solve the issue?

I am running:

- "react-native": "0.60.3",
-  "@react-native-community/audio-toolkit": "^2.0.2",
- iOS 12.3.1

**Comment by defrian** [comment]
I was able to fix the issue by

`[audioSession setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionAllowBluetooth error:&error];`

solution found here: https://stackoverflow.com/a/46695136

created pullrequest #169
