### ISSUE TITLE
This library needs some attention.

### ISSUE THREAD

**Issue by seriiix** [react-native-community/react-native-audio-toolkit#140]
The whole point of `react-native-community` was better supporting the community-oriented libraries, but this one does not get any updates in a long time. Many issues and relevant PRs are open like [https://github.com/react-native-community/react-native-audio-toolkit/pull/112](https://github.com/react-native-community/react-native-audio-toolkit/pull/112), and there's no maintainer to review and merge these PRs.

**Comment by sibelius** [comment]
Do you want to help review issue and pull requests?

**Comment by sbeca** [comment]
As a new contributor, I'll be starting to review, test, and merge PRs this weekend

**Comment by seriiix** [comment]
@sibelius Thanks for inviting me. I'm new to collaborating but I'll try to help and fix problems.
@sbeca That would be amazing thank you!
