### ISSUE TITLE
Can't resume after pause

### ISSUE THREAD

**Issue by maitrungduc1410** [react-native-community/react-native-audio-toolkit#156]
I'm noticing that the `playPause()` or `pause()` make the player stopped but the currentTime is still increase. I can't resume my player even it I call `playPause()` or `play` again.

Can someone confirm me?

Thank you

**Comment by stillyu** [comment]
same issue

**Comment by maitrungduc1410** [comment]
I finally ended up with switch to `react-native-sound`, it works fine.

This is my [example code](https://gist.github.com/maitrungduc1410/510283f598bd28f3c7868c96159944e1)

**Comment by xstable** [comment]
Isn't it fixed now by this Release? : https://github.com/react-native-community/react-native-audio-toolkit/releases/tag/v2.0.0

**Comment by maitrungduc1410** [comment]
> Isn't it fixed now by this Release? : https://github.com/react-native-community/react-native-audio-toolkit/releases/tag/v2.0.0

Great, I will give it a try
