### ISSUE TITLE
 Not compiled properly

### ISSUE THREAD

**Issue by PL-SQL** [react-native-community/react-native-audio-toolkit#164]
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-audio-toolkit.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-audio-toolkit:
          - None of the consumable configurations have attributes.

**Comment by epoxa** [comment]
@PL-SQL  how did you manage to fix the issue?

**Comment by PL-SQL** [comment]
@epoxa 
yarn add @react-native-community/audio-toolkit

**Comment by jakubmas** [comment]
Hey, I have the same problem but even after react-native-community/audio-toolkit installation it gives me the same error. What causes this error?
