### ISSUE TITLE
Audio stops playing after leaving app open 

### ISSUE THREAD

**Issue by taylorpringle** [react-native-community/react-native-audio-toolkit#181]
We have found an issue where the audio stops playing after the app has been left open for a while. The audio wont play through the app until it is shut down and reopened. 

Has anyone had an issue like this?

We are trying to find a solution but cant find an error or issue as to why it has been happening.

Occurs on iOS, have not tested on Android

**Comment by taylorpringle** [comment]
@youngwiseone

**Comment by kodusu** [comment]
Same thing happened to me on Android too. Audios not playing after certain time. I tested it on Android 5 & 6 Versions

**Comment by HieuDevX** [comment]
I'm having same issue on android 8 :( Have any ideas?

**Comment by kodusu** [comment]
I moved to [ react-native-video](https://github.com/react-native-community/react-native-video) which is working great on all the versions. This library has audioOnly feature which can help to play audio files with out video

**Comment by taylorpringle** [comment]
I ended up moving to [react-native-track-player](https://github.com/react-native-kit/react-native-track-player) which seems to be working great so far.
