### ISSUE TITLE
Android MediaPlayer error code -38

### ISSUE THREAD

**Issue by eambutu** [react-native-community/react-native-audio-toolkit#182]
I haven't been able to play any videos. I initially thought it was because I was trying to play .webm files, but the problem also occurs for .mp3 files, and also even if I download them locally. My code is super simple, basically the sample code. The error I get is: 

`{"err": {"extra": 0, "what": -38}, "message": "Android MediaPlayer error"}`

I tried looking up this error code in the Android MediaPlayer, but found nothing...

**Comment by UsamaShakeel** [comment]
I was facing the same issue.

I commented line number **358** in **AudioPlayerModule.java** file and it worked.

Turns out if we pause media player before playing it this error is thrown.

<img width="1002" alt="Screenshot 2019-11-07 at 12 01 35 PM" src="https://user-images.githubusercontent.com/1985600/68367035-86e21480-0156-11ea-818e-84ba0f8a8cd6.png">

**Comment by Aung-Myint-Thein** [comment]
I am getting the same error but didn't do any pause or any fancy thing. I just create the player and play and get this error. Any suggestion or solution have you guys found? @eambutu @UsamaShakeel

**Comment by EzeMortal** [comment]
I have the same problem on Samsung Note 4, Android 6.0. 
Nothing complex here
```javascript
const player = new Player(music)
player.volume = 0.2

player.on('ended', (data) => { })

player.on('error', (data) => {
   console.log(data)
})

player.play()
```

**Comment by EzeMortal** [comment]
> 
> 
> I was facing the same issue.
> 
> I commented line number **358** in **AudioPlayerModule.java** file and it worked.
> 
> Turns out if we pause media player before playing it this error is thrown.
> 
> <img alt="Screenshot 2019-11-07 at 12 01 35 PM" width="1002" src="https://user-images.githubusercontent.com/1985600/68367035-86e21480-0156-11ea-818e-84ba0f8a8cd6.png">

This fixed the error thanks!
I don't think that this is the real "fix", there will be some bug somewhere
