### ISSUE TITLE
File not created on android

### ISSUE THREAD

**Issue by emmanuelfrancis** [react-native-community/react-native-audio-toolkit#226]
Used sample code, but file does not get created on android.

recorder = new Recorder('filename.mp4', {
        bitrate: 128000,
        channels: 2, 
        sampleRate: 44100,
        // quality: 'high',
        format: 'mp4',
        encoder: 'aac-lc',
      }).prepare((err, fsPath) => {
          console.log('prepare What error: ', err);
          console.log('prepare What file path: ', fsPath);
      });
      recorder.toggleRecord((err, stopped) => {
        
      });

I get an error in log as follows:
`06-23 23:22:45.326 297-29062/? E/OMXNodeInstance: setConfig(47:google.aac.encoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
06-23 23:22:45.326 297-29062/? I/ACodec: codec does not support config priority (err -2147483648)
06-23 23:22:45.327 297-3023/? I/MediaCodec: (0xb85103a0) start
06-23 23:22:45.327 297-29062/? I/MediaCodec: (0xb85103a0) input buffers allocated
06-23 23:22:45.327 297-29062/? I/MediaCodec: (0xb85103a0) numBuffers (4)
06-23 23:22:45.327 297-29062/? I/MediaCodec: (0xb85103a0) output buffers allocated
06-23 23:22:45.327 297-29062/? I/MediaCodec: (0xb85103a0) numBuffers (4)
06-23 23:22:45.327 297-3023/? I/MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: 128000 bps and the estimated moov size 3195 bytes
06-23 23:22:45.327 297-29059/? I/MediaCodecSource: MediaCodecSource (audio) starting
06-23 23:22:45.328 297-29061/? D/audio_hw_primary: in_set_parameters: enter: kvpairs=input_source=1;routing=-2147483644
06-23 23:22:45.330 297-29059/? I/MediaCodecSource: MediaCodecSource (audio) started
06-23 23:22:45.331 297-29062/? I/MediaCodec: (0xb85103a0) codec output format changed
06-23 23:22:45.331 297-29062/? D/MediaCodec: (0xb85103a0) output format: AMessage(what = 'codc', target = 248) = {
       string mime = "audio/mp4a-latm"
       int32_t channel-count = 2
       int32_t sample-rate = 44100
       int32_t aac-profile = 5
       int32_t what = 1869968451
     }`

**Comment by emmanuelfrancis** [comment]
I was looking at incorrect path. Thanks.

**Comment by oshri-humanz** [comment]
File is not created for me as well, I get "Could not retrieve file for contentUri" error when trying to obtain the file
How did you resolved it?
