### ISSUE TITLE
No sound when built in Testflight on iOs

### ISSUE THREAD

**Issue by davidfloegel** [react-native-community/react-native-audio-toolkit#228]
# Question

Hi there,

So I've implemented the audio toolkit according to the documentation and I've added my sound files to the bundle (right click -> add files to project) in XCode.

My problem is, it's working fine in the development (both on simulator + device) but as soon as I build the project and run it either on the simulator, device or publish through XCode I get no sound.

Has anyone else had that issue?

**Comment by erez-git** [comment]
Hi, did you find a solution? I have the same problem. Thanks!

**Comment by nikiyasimpson** [comment]
I am having the same issue.

**Comment by erez-git** [comment]
> I am having the same issue.

Just run the app via xCode in Release mode and it won't play the sound as well. It was a bug in the code. I've no idea what was the solution but at least you hopefully can test it :)

**Comment by nikiyasimpson** [comment]
I added a line to add Info.plist and I'm going to test again to see if this works for my issue. It was just crashing when I tried to record.

	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires access to your microphone for speech-based reporting</string>

**Comment by erez-git** [comment]
oh ok, got it. So in my situation it didn't crash in Release mode but didn't play the sound.

**Comment by Sowji999** [comment]
Any one fixed the same issue??? There was no crash but in Development mode sound is coming Release mode sound is not coming. Please help me out if anyone found the solution for this.

**Comment by Sowji999** [comment]
> # Question
> Hi there,
> 
> So I've implemented the audio toolkit according to the documentation and I've added my sound files to the bundle (right click -> add files to project) in XCode.
> 
> My problem is, it's working fine in the development (both on simulator + device) but as soon as I build the project and run it either on the simulator, device or publish through XCode I get no sound.
> 
> Has anyone else had that issue?

Did You find the solution???

**Comment by Sowji999** [comment]
> Hi, did you find a solution? I have the same problem. Thanks!

Did you got solution?

**Comment by elburu** [comment]
Hi there, same issue here, do you find any solution??
