### ISSUE TITLE
player.stop does not work

### ISSUE THREAD

**Issue by sdattatri** [react-native-community/react-native-audio-toolkit#241]
# Bug report
Hi!
## Summary
Player.stop gets called but does not actually stop the playing when called from inside useLayoutEffect with navigation.setOptions.  The player.stop function gets called and the subsequently the stop callback is also called successfully.  However, the audio continues to play.

## Environment info
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 2.10 GB / 7.89 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 24, 25, 28, 29
      Build Tools: 21.1.2, 22.0.1, 23.0.3, 24.0.1, 25.0.0, 25.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_211
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
Library version: x.x.x

## Steps to reproduce
Here is the corresponding code snippet.   The same code inside onPress works correctly when called from within a button in the screen.

```
React.useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <TouchableOpacity
          activeOpacity={0.3}
          onPress={() => {
            if (localPlayer) {
              localPlayer.stop(() => {
                navigation.navigate('Settings');
              });
            }
          }}>
          <Ionicons style={styles.actionButton} name="settings-outline" />
        </TouchableOpacity>
      ),
    });
  }, [navigation]);

```

**Comment by KrisLau** [comment]
did you ever figure this out? I cant seem to stop my player at all:
```
const player = new Player(.audioUrl);

if (isPlaying) {
    player.stop();
} else {
    player.play();
}
```

**Comment by eflashcards** [comment]
+1

**Comment by KrisLau** [comment]
Probably avoid this package for anyone looking at this now. It's been abandoned since 2020  from what I can tell. I'd recommend expo-av or react-native-track-player instead
